AuctionsWebsite/AuctionsWebsite/Controllers/AuctionController.cs
using Contracts;
using Entities.DTO.Auction;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace AuctionsWebsite.Controllers
{
    [Authorize]
    public class AuctionController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IUnitOfWork _repository;

        public AuctionController(ILoggerManager logger, IUnitOfWork repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public IActionResult Index()
        {
            try
            {
                var wallet = _repository.Wallet.GetWalletForUser(Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == "uid")?.Value));

                if (wallet == null)
                {
                    ViewBag.Result = "There isn't any wallet for this user!";
                    return View();
                }

                var auctions = _repository.Auction.GetAuctions();

                var dto = new CurrentAuctionsDTO { CurrentWalletAmount = wallet.Amount, Auctions = auctions };

                return View(dto);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong getting auctions: {ex.Message}!");
                ViewBag.Result = "There was an error getting data from database! Please try again later!";

                return View();
            }
        }

        public IActionResult Details(int id)
        {
            try
            {
                ViewBag.AmountErr = TempData["AmountErr"];
                ViewBag.Result = TempData["Result"];
                ViewBag.EndAuctionErr = TempData["EndAuctionErr"];

                var details = _repository.Auction.GetAuctionDetails(id);

                return View(details);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside Delete action: {ex.Message}!");
                ViewBag.Result = "There was an error deleting the auction! Please try again later!";

                return View();
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AuctionDTO auction)
        {
            if (!ModelState.IsValid)
                return View(auction);

            try
            {
                var prod = _repository.Product.GetProduct(auction.ProductName, auction.ProductDescription);

                if (prod == null)
                {
                    ModelState.AddModelError("ProductName", "Product name does not exist!");
                    ModelState.AddModelError("ProductDescription", "Product description does not exist!");

                    return View(auction);
                }

                var uid = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "uid")?.Value;

                if (string.IsNullOrWhiteSpace(uid))
                {
                    _logger.LogError($"Something went wrong inside Create action: Couldn't fetch userId!");

                    ViewBag.Result = "There was an error creating the auction! Please try again later!";
                    return View(auction);
                }

                _repository.Auction.CreateAuction(auction, prod.Id, Convert.ToInt32(uid));
                _repository.Save();

                ViewBag.Result = "Auction created successfully!";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside Create action: {ex.Message}!");
                ViewBag.Result = "There was an error creating the auction! Please try again later!";

                return View(auction);
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                var auction = _repository.Auction.GetAuctionById(id);

                if (auction == null)
                    ViewBag.Result = "The auction doesn't exist!";

                else
                {
                    _repository.Auction.DeleteAuction(auction);
                    _repository.Save();
                }

            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside Delete action: {ex.Message}!");
                ViewBag.Result = "There was an error deleting the auction! Please try again later!";
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EndAuction(int id)
        {
            try
            {
                var auction = _repository.Auction.GetAuctionDetails(id);

                if (auction == null)
                    return RedirectToAction("Index");

                _repository.Auction.EndAuction(auction);
                _repository.Save();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside EndAuction action: {ex.Message}!");
                TempData["EndAuctionErr"] = "There was an error ending the auction! Please try again later!";

                return RedirectToAction("Details", new { id });
            }

            return RedirectToAction("Index");
        }
    }
}

AuctionsWebsite/AuctionsWebsite/Controllers/AuthController.cs
using AuctionsWebsite.Models;
using Contracts;
using Entities.DTO.Auth;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AuctionsWebsite.Controllers
{
    public class AuthController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IUnitOfWork _repository;

        public AuthController(ILoggerManager logger, IUnitOfWork repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginDTO loginObj)
        {
            if (!ModelState.IsValid)
                return View(loginObj);

            try
            {
                var user = _repository.Auth.Login(loginObj);

                if (user != null)
                {
                    var claims = new[]
                    {
                        new Claim(ClaimTypes.Name, user.Username),
                        new Claim("uid", user.Id.ToString())
                    };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(identity));

                    return RedirectToAction("Index", "Auction");
                }

                else
                    ViewBag.Result = "User not found!";

                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside Login action: {ex.Message}!");
                ViewBag.Result = "There was an error trying to authenticate! Please try again later!";
            }

            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterDTO registerObj)
        {
            if (!ModelState.IsValid)
                return View(registerObj);

            try
            {
                bool isPresent = _repository.Auth.GetByUsername(registerObj.Username);

                if (isPresent)
                    ViewBag.Result = "There exists a user with the same credentials!";

                else
                {
                    _repository.Auth.Register(registerObj);
                    _repository.Save();

                    ViewBag.Result = "User registered successfully!";

                    return RedirectToAction("Login");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside Register action: {ex.Message}!");
                ViewBag.Result = "There was an error trying to register user! Please try again later!";
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Login");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AuctionsWebsite/AuctionsWebsite/Controllers/BidController.cs
using Contracts;
using Entities.DAO.Bid;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace AuctionsWebsite.Controllers
{
    [Authorize]
    public class BidController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IUnitOfWork _repository;

        public BidController(ILoggerManager logger, IUnitOfWork repository)
        {
            _logger = logger;
            _repository = repository;
        }

        [HttpPost]
        public IActionResult PlaceBid(int id, double amount)
        {
            try
            {
                var auctionDetails = _repository.Auction.GetAuctionDetails(id);

                if(amount < auctionDetails.StartingBid)
                {
                    TempData["AmountErr"] = "Input amount is lower than the starting bid!";
                    return RedirectToAction("Details", "Auction", new { id });
                }

                if (amount <= auctionDetails.HighestBidAmount)
                {
                    TempData["AmountErr"] = "Input amount is lower than the highest bid!";
                    return RedirectToAction("Details", "Auction", new { id });
                }

                var userId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == "uid")?.Value);

                var wallet = _repository.Wallet.GetWalletForUser(userId);

                if (wallet == null)
                {
                    TempData["Result"] = "Wallet not found for user!";
                    return RedirectToAction("Details", "Auction", new { id });
                }

                if (amount > wallet.Amount)
                {
                    TempData["AmountErr"] = "Input amount is greater than the users wallet!";
                    return RedirectToAction("Details", "Auction", new { id });
                }

                _repository.Bid.PlaceBid(new BidDAO { AuctionId = id, Amount = amount, UserId = userId });
                _repository.Save();

                return RedirectToAction("Index", "Auction");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside PlaceBid action: {ex.Message}!");
                TempData["Result"] = "There was an error placing the bid! Please try again later!";
                return RedirectToAction("Details", "Auction", new { id });
            }
        }
    }
}

AuctionsWebsite/AuctionsWebsite/Views/Auction/Create.cshtml
@model Entities.DTO.Auction.AuctionDTO

@{
    ViewData["Title"] = "New Auction Page";
}

<div>
    <div style="float:right; display: flex">
        <h1 class="display-4">New Auction</h1>
        @Html.ActionLink("Home", "Index", "Auction")
        @using (Html.BeginForm("Logout", "Auth", FormMethod.Post))
        {
            <input type="submit" value="Logout" style="background: none !important; border: none; padding: 0 !important; cursor: pointer; color: blue; margin-left: 10px" />
        }
    </div>

    @using (Html.BeginForm("Create", "Auction", FormMethod.Post))
    {
        <div>
            <table>
                <tr>
                    <td>
                        @Html.Label("Product Name")
                        @Html.TextBoxFor(p => p.ProductName)
                        @Html.ValidationMessageFor(p => p.ProductName)
                    </td>
                    <td>
                        @Html.Label("Starting Bid")
                        @Html.TextBoxFor(a => a.StartingBid, new { @type = "number" })
                        @Html.ValidationMessageFor(a => a.StartingBid)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.Label("Product Description")
                        @Html.TextAreaFor(p => p.ProductDescription)
                        @Html.ValidationMessageFor(p => p.ProductDescription)
                    </td>
                    <td>
                        @Html.Label("End Date")
                        @Html.TextBoxFor(a => a.EndDate, new { @type = "date" })
                        @Html.ValidationMessageFor(a => a.EndDate)
                    </td>
                </tr>
            </table>
            <input type="submit" value="Create Auction" />
            @ViewBag.Result
        </div>
    }
</div>

AuctionsWebsite/AuctionsWebsite/Views/Auction/Details.cshtml
@model Entities.DTO.Auction.AuctionDetailsDTO

@{
    ViewData["Title"] = "Auction Details Page";
}

<div>
    <h1 class="display-4">Current Auctions</h1>
    <div style="float:right; display: flex">
        @Html.ActionLink("Home", "Index", "Auction")
        @using (Html.BeginForm("Logout", "Auth", FormMethod.Post))
        {
            <input type="submit" value="Logout" style="background: none !important; border: none; padding: 0 !important; cursor: pointer; color:blue; margin-left:10px" />
        }
    </div>

    <div>
        <table>
            <tr>
                <td>
                    @Html.DisplayFor(m => m.ProductName)
                </td>
                <td>
                    Created by: @Html.DisplayFor(m => m.SellerName)
                </td>
            </tr>
            <tr>
                <td>
                    Time remaining: @Html.DisplayFor(m => m.TimeRemaining) days
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(m => m.ProductDescription)
                </td>
            </tr>
            <tr>
                <td>
                    Current highest bid: @Html.DisplayFor(m => m.HighestBidAmount)
                </td>
                <td>
                    By: @Html.DisplayFor(m => m.HighestBidName)
                </td>
            </tr>
        </table>
    </div>

    @*if i created the auction and there is at least one bid*@

    @if (Model.SellerId.ToString() == Context.User.Claims.FirstOrDefault(c => c.Type == "uid")?.Value && Model.HighestBidUserId > 0)
    {
        @using (Html.BeginForm("EndAuction", "Auction", new { Id = Model.Id }, FormMethod.Post))
        {
            <input type="submit" value="End Auction" />
        }
        @ViewBag.EndAuctionErr
    }

    //if i didn't create the auction show bid button
    else if (Model.SellerId.ToString() != Context.User.Claims.FirstOrDefault(c => c.Type == "uid")?.Value)
    {
        <div style="float:right;">
            @using (Html.BeginForm("PlaceBid", "Bid", new { Id = Model.Id }, FormMethod.Post))
            {
                @Html.Hidden("HighestBid", Model.HighestBidAmount)
                @Html.TextBox("Amount")
                <br />
                @ViewBag.AmountErr
                <br />

                <input type="submit" value="Bid" />
            }
            @ViewBag.Result
        </div>
    }
</div>

AuctionsWebsite/AuctionsWebsite/Views/Auction/Index.cshtml
@model Entities.DTO.Auction.CurrentAuctionsDTO

@{
    ViewData["Title"] = "Auction Page";
}

<div>
    <h1 class="display-4">Current Auctions</h1>
    <div style="float:right; display: flex">
        Hi @Context.User.Identity.Name!
        @using (Html.BeginForm("Logout", "Auth", FormMethod.Post))
        {
            <input type="submit" value="Logout" style="background: none !important; border: none; padding: 0 !important; cursor: pointer; color:blue; margin-left:10px" />
        }
    </div>

    <div>
        <table class="table table-bordered table-responsive table-hover" style="width:stretch">
            <tr>
                <th>
                    @Html.DisplayName("Product")
                </th>
                <th>
                    @Html.DisplayName("Seller")
                </th>
                <th>
                    @Html.DisplayName("Top Bid")
                </th>
                <th>
                    @Html.DisplayName("Time remaining")
                </th>
                <th>
                </th>
            </tr>
            @foreach (var item in Model.Auctions)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Product, "Details", new { id = item.Id })
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Seller)
                    </td>
                    <td>
                        $@Html.DisplayFor(m => item.TopBid)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.TimeRemaining) Days
                    </td>
                    <td>
                        @if (Context.User.Claims.FirstOrDefault(c => c.Type == "uid")?.Value == item.SellerId.ToString())
                        {
                            @using (Html.BeginForm("Delete", "Auction", new { Id = item.Id }, FormMethod.Post))
                            {
                                <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this record?');"
                                       style="background: none !important; border: none; padding: 0 !important; text-decoration: underline; cursor: pointer; color: blue;" />
                            }
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div>
        <div style="float:left">
            @Html.ActionLink("New Auction", "Create")
        </div>
        <div style="float:right">
            Your Current Wallet: $@Html.DisplayFor(m => m.CurrentWalletAmount)
        </div>
        @ViewBag.Result
    </div>
</div>